export const AUTHENTICATE = "AUTHENTICATE";
export const LOGOUT = "LOGOUT";

// Event types
export const SET_ALL_EVENT_TYPES = "SET_ALL_EVENT_TYPES";
export const UPDATE_USER_PROFILE = "UPDATE_USER_PROFILE";
export const CONFIRMED = "CONFIRMED";
export const CLEAR_CONFIRMATION = "CLEAR_CONFIRMATION";
export const SET_AVAILABLE_SLOTS = "SET_AVAILABLE_SLOTS";
export const CLEAR_AVAILABLE_SLOTS = "CLEAR_AVAILABLE_SLOTS";

// Profile
export const UPDATE_WELCOME_MESSAGE = "UPDATE_WELCOME_MESSAGE";

// UI
export const SET_LOADING = "SET_LOADING";
export const UNSET_LOADING = "UNSET_LOADING";
export const SET_SUBMITTING = "SET_SUBMITTING";
export const SUCCESS = "SUCCESS";
